import Head from "next/head";
import axios from "axios";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <div className="flex justify-center items-center pb-4 font-bold text-2xl">
          Topics To Bet
        </div>
        <div className="grid grid-cols-1 gap-4">
          {data?.map((el, i) => (
            <div key={i} className="flex justify-around items-center">
              <Link
                href={`topic/${el["_id"]["$oid"]}`}
                className="lg:col-span-2 col-span-1 bg-white justify-between w-full border p-2 lg:p-4 rounded-lg"
              >
                <div className="flex flex-col w-full pb-4">
                  <p className="text-2xl font-medium">{el.topic_name}</p>
                  <p className="text-gray-600">
                    Status : {el.topic_is_running ? "Ongoing" : "Completed"}
                  </p>
                  <p className="text-gray-600">This Side : {el.topic_side_a}</p>
                  <p className="text-gray-600">That Side : {el.topic_side_b}</p>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    const res = await axios.get("/api/topics");
    const data = res.data.reverse();
    return { props: { data } };
  } catch (error) {
    console.log(error);
    return { props: { data: null } };
  }
}
