import Head from "next/head";
import { Inter } from "@next/font/google";
import Bet from "@/Components/Bet";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <div className="flex justify-around items-center">
          <div className="w-full">
            <Bet />
          </div>
          <div className="w-full text-center text-8xl italic text-yellow-600">
            VS
          </div>
          <div className="w-full">
            <Bet />
          </div>
        </div>
      </main>
    </>
  );
}
